sudo: required
services:
  - docker

before_install:
  - docker build -t 1443363/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 1443363/react-test npm test

after_success:
  - docker build -t 1443363/multi-client ./client
  - docker build -t 1443363/multi-nginx ./nginx
  - docker build -t 1443363/multi-server ./server
  - docker build -t 1443363/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push 1443363/multi-client
  - docker push 1443363/multi-nginx
  - docker push 1443363/multi-server
  - docker push 1443363/multi-worker